[package]
name = "poc-environment"
version = "0.1.0"
authors = ["Nguyen Marc <nguyen_marc@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
