on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: target/release/

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  deploy-dev:
    name: Deploy to dev
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [build, fmt, clippy]
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Download static content from artifact
        uses: actions/download-artifact@v2
        with:
          name: release
          path: target/release/
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release

  deploy-staging:
    name: Deploy to staging
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, fmt, clippy]
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Download static content from artifact
        uses: actions/download-artifact@v2
        with:
          name: release
          path: target/release/
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release

  deploy-prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Download static content from artifact
        uses: actions/download-artifact@v2
        with:
          name: release
          path: target/release/
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release
